"""add recovery action case foreign key

Revision ID: 1d6429f56755
Revises: ce23682d5698
Create Date: 2026-08-31 20:34:06.743599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d6429f56755'
down_revision: Union[str, Sequence[str], None] = 'ce23682d5698'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'recovery_actions', 'recovery_cases', ['case_id'], ['case_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recovery_actions', type_='foreignkey')
    # ### end Alembic commands ###
