"""create payment attempts table

Revision ID: 6b258a6b7048
Revises: d5265df226e1
Create Date: 2026-08-31 19:35:14.706189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b258a6b7048'
down_revision: Union[str, Sequence[str], None] = 'd5265df226e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_attempts',
    sa.Column('attempt_id', sa.String(length=100), nullable=False),
    sa.Column('payment_id', sa.String(length=100), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('attempt_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment_attempts')
    # ### end Alembic commands ###
