"""add payment customer foreign key

Revision ID: 6c372c03a302
Revises: f145687673a7
Create Date: 2026-08-31 20:12:44.017230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c372c03a302'
down_revision: Union[str, Sequence[str], None] = 'f145687673a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'payments', 'customers', ['customer_id'], ['customer_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payments', type_='foreignkey')
    # ### end Alembic commands ###
