"""add audit event case foreign key

Revision ID: 76b3fe9d369a
Revises: b1144551d8e2
Create Date: 2026-08-31 21:37:19.817472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76b3fe9d369a'
down_revision: Union[str, Sequence[str], None] = 'b1144551d8e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'audit_events', 'recovery_cases', ['case_id'], ['case_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'audit_events', type_='foreignkey')
    # ### end Alembic commands ###
