"""add recovery outcome foreign keys

Revision ID: b1144551d8e2
Revises: 1d6429f56755
Create Date: 2026-08-31 20:39:46.884878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1144551d8e2'
down_revision: Union[str, Sequence[str], None] = '1d6429f56755'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'recovery_outcomes', 'recovery_actions', ['action_id'], ['action_id'])
    op.create_foreign_key(None, 'recovery_outcomes', 'recovery_cases', ['case_id'], ['case_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recovery_outcomes', type_='foreignkey')
    op.drop_constraint(None, 'recovery_outcomes', type_='foreignkey')
    # ### end Alembic commands ###
