"""create risk assessments table

Revision ID: c7e86e871cce
Revises: f4b73f875b54
Create Date: 2026-08-31 19:45:06.443868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7e86e871cce'
down_revision: Union[str, Sequence[str], None] = 'f4b73f875b54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('risk_assessments',
    sa.Column('assessment_id', sa.String(length=100), nullable=False),
    sa.Column('case_id', sa.String(length=100), nullable=False),
    sa.Column('amount_at_risk', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('recoverability_score', sa.Float(), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('assessed_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('assessment_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('risk_assessments')
    # ### end Alembic commands ###
