"""add recovery decision case foreign key

Revision ID: ce23682d5698
Revises: d4483d858215
Create Date: 2026-08-31 20:28:58.513635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce23682d5698'
down_revision: Union[str, Sequence[str], None] = 'd4483d858215'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'recovery_decisions', 'recovery_cases', ['case_id'], ['case_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recovery_decisions', type_='foreignkey')
    # ### end Alembic commands ###
