"""add recovery case payment foreign key

Revision ID: d4483d858215
Revises: 6c372c03a302
Create Date: 2026-08-31 20:25:04.628603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4483d858215'
down_revision: Union[str, Sequence[str], None] = '6c372c03a302'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'recovery_cases', 'payments', ['payment_id'], ['payment_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recovery_cases', type_='foreignkey')
    # ### end Alembic commands ###
