"""create recovery decisions table

Revision ID: f4b73f875b54
Revises: 93c4391a71a1
Create Date: 2026-08-31 19:42:06.578637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4b73f875b54'
down_revision: Union[str, Sequence[str], None] = '93c4391a71a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recovery_decisions',
    sa.Column('decision_id', sa.String(length=100), nullable=False),
    sa.Column('case_id', sa.String(length=100), nullable=False),
    sa.Column('recommended_action', sa.String(length=100), nullable=False),
    sa.Column('confidence', sa.String(length=20), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('decision_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recovery_decisions')
    # ### end Alembic commands ###
